# Generated by Django 3.0.3 on 2025-01-09 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asamblea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('link', models.URLField()),
                ('fecha', models.DateTimeField()),
                ('longitud', models.FloatField()),
                ('latitud', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficha', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(max_length=50)),
                ('regimen_contractual', models.CharField(max_length=50)),
                ('departamento', models.CharField(max_length=50)),
                ('clave_centro_trabajo', models.CharField(max_length=20)),
                ('centro_trabajo', models.CharField(max_length=100)),
                ('longitud', models.FloatField()),
                ('latitud', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmacion', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('asamblea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asambleas.Asamblea')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asambleas.Trabajador')),
            ],
            options={
                'unique_together': {('trabajador', 'asamblea')},
            },
        ),
    ]
