# Generated by Django 3.0.3 on 2025-01-09 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asambleas', '0002_auto_20250109_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='longitud',
        ),
    ]
