# Generated by Django 3.0.3 on 2025-01-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asambleas', '0005_auto_20250109_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='departamento',
            field=models.CharField(max_length=100),
        ),
    ]
